document.writeln("<!--侧边-->");
document.writeln("<nav class=\"col-md-2 \" id=\"sidebar\">");
document.writeln("    <div >");
document.writeln("        <ul class=\"nav nav-pills nav-stacked \" >");
document.writeln("            <li role=\"presentation\" >");
document.writeln("                <a href=\"crud_write.html\" ><span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span>发布文章</a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li role=\"presentation\" >");
document.writeln("                <a href=\"crud_list.html\" ><span class=\"glyphicon glyphicon-th\" aria-hidden=\"true\"></span>文章管理</a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li role=\"presentation\"  >");
document.writeln("                <a href=\"crud_gallery.html\"> <span class=\"glyphicon glyphicon-th\" aria-hidden=\"true\"></span>图片管理</a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("            <li role=\"presentation\" >");
document.writeln("                <a href=\"#\" id=\"logout\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span>退出</a>");
document.writeln("            </li>");
document.writeln("");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</nav>");