document.writeln("<div class=\"left\">");
document.writeln("				<div class=\"pos\">");
document.writeln("					<b>当前位置：</b>");
document.writeln("					<a href=\"index.html\" >首页</a>");
document.writeln("					>");
document.writeln("					<a id = \"localA\"></a>");
document.writeln("				</div>");
document.writeln("				<div>");
document.writeln("					<img src=\"img/分割.png\" />");
document.writeln("				</div>");
document.writeln("				<div class=\"link\">");
document.writeln("					<a href=\"index_article.html?type=项目组介绍\" >");
document.writeln("						<div>> 项目组介绍</div>");
document.writeln("						<span>></span>");
document.writeln("					</a>");
document.writeln("					<a href=\"index_list.html?type=项目案例/成果\" >");
document.writeln("						<div>> 项目案例/成果</div>");
document.writeln("						<span>></span>");
document.writeln("					</a>");
document.writeln("					<a href=\"index_article.html?type=实验室介绍\" >");
document.writeln("						<div>> 实验室介绍</div>");
document.writeln("						<span>></span>");
document.writeln("					</a>");
document.writeln("				</div>");
document.writeln("			</div>");