document.writeln("<div class=\'footer\'>");
document.writeln("			<div class=\'ff center\'>");
document.writeln("				<div class=\'f1 fl\'>");
document.writeln("					<table>");
document.writeln("						<tr>");
document.writeln("							<th><p>关于团队</p></th>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>团队介绍</a></td>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>团队文化</a></td>");
document.writeln("						</tr>");
document.writeln("					</table>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'f1 fl\'>");
document.writeln("					<table>");
document.writeln("						<tr>");
document.writeln("							<th><p>团队服务</p></th>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>服务范围</a></td>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>服务理念</a></td>");
document.writeln("						</tr>");
document.writeln("					</table>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'f1 fl\'>");
document.writeln("					<table>");
document.writeln("						<tr>");
document.writeln("							<th><p>联系我们</p></th>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>联系方式</a></td>");
document.writeln("						</tr>");
document.writeln("						<tr>");
document.writeln("							<td><a href=\'\' target=\'_blank\'>招贤纳士</a></td>");
document.writeln("						</tr>");
document.writeln("					</table>");
document.writeln("				</div>");
document.writeln("");
document.writeln("				<div class=\'f2 fl\'>");
document.writeln("					<div></div>");
document.writeln("					<p>团队微信</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</div>");