document.writeln("<header>");
document.writeln("<div class=\'tlogo\'><img src=\'img/LOGO.png\'></div><!--头部LOGO-->");
document.writeln("<div class=\'nav\'>");
document.writeln("	<div class=\'nav1 center\'>");
document.writeln("		<ul>");
document.writeln("			<li><a href=\'index.html\'>首页</a></li>");
document.writeln("			<li><a href=\'index_article.html\'>项目组介绍</a></li>");
document.writeln("			<li><a href=\'index_list.html\'>项目案例/成果</a></li>");
document.writeln("			<li><a href=\'index_list.html\'>学术动态</a></li>");
document.writeln("			<li><a href=\'index_article.html\'>实验室介绍</a></li>");
document.writeln("			<li><a href=\'\'>联系我们</a></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("		<!-- 画廊-->");
document.writeln("		<div class=\"slider\">");
document.writeln("			<div id=\"myCarousel\" class=\"carousel slide\">");
document.writeln("				<!-- 轮播（Carousel）指标 -->");
document.writeln("				<ol class=\"carousel-indicators\">");
document.writeln("					<!-- 轮播（Carousel）指标   小圆点-->");
document.writeln("				</ol>");
document.writeln("				<!-- 轮播（Carousel）项目 -->");
document.writeln("				<div class=\"carousel-inner\">");
document.writeln("					<!--画廊图片-->");
document.writeln("				</div>");
document.writeln("				<!-- 轮播（Carousel）导航 -->");
document.writeln("				<a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">");
document.writeln("					<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>");
document.writeln("					<span class=\"sr-only\">Previous</span>");
document.writeln("				</a>");
document.writeln("				<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">");
document.writeln("					<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>");
document.writeln("					<span class=\"sr-only\">Next</span>");
document.writeln("				</a>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</header>");