document.writeln("<div class=\'footer\'>");
document.writeln("			<div class=\'ff center\'>");
document.writeln("				<div class=\'fl f1\'>");
document.writeln("					<img src=\'img/LOGO.png\' class=\'flogo\'>");
document.writeln("				</div>");
document.writeln("				<div class=\'fl f2\'>");
document.writeln("					<div><img src=\'img/phone_icon.png\'><span>&nbsp;电话：0756-3622745 招生咨询电话：0756-3622966</span></div>");
document.writeln("					<div><img src=\'img/locate_icon.png\'><span>&nbsp;地址:广东省珠海市唐家湾金凤路6号 邮编：519088</span></div>");
document.writeln("					<div><img src=\'img/mail_icon.png\'><span>&nbsp;邮箱：zhbit@zhbit.com </span></div>");
document.writeln("				</div>");
document.writeln("");
document.writeln("");
document.writeln("				<div class=\'f3 fr\'>");
document.writeln("					<div></div>");
document.writeln("					<p>官方微信</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("			<div class=\'f4 center\'><span>版权所有©比芯创客 BECOREMAKER</span></div>");
document.writeln("");
document.writeln("		</div>");