document.writeln("<div class=\'left\'>");
document.writeln("				<div class=\'pos\'>");
document.writeln("					<div class=\'pos1\'>");
document.writeln("						<b>当前位置：</b>");
document.writeln("						<a href=\'index.html\' target=\'_parent\'>首页</a>");
document.writeln("						<b>> <b/>");
document.writeln("						<a href=\'MORE.html\' target=\'_parent\'>学术动态</a>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<div class=\'link\'>");
document.writeln("					<a href=\'\' target=\'_blank\'>");
document.writeln("						<div>");
document.writeln("							<span><div></div></span>");
document.writeln("							<span><p> 项目组介绍</p></span>");
document.writeln("						</div>");
document.writeln("					</a>");
document.writeln("					<a href=\'\' target=\'_blank\'>");
document.writeln("						<div>");
document.writeln("							<span><div></div></span>");
document.writeln("							<span><p> 项目案例/成果</p></span>");
document.writeln("						</div>");
document.writeln("					</a>");
document.writeln("					<a href=\'\' target=\'_blank\'>");
document.writeln("						<div>");
document.writeln("							<span><div></div></span>");
document.writeln("							<span><p> 实验室介绍</p></span>");
document.writeln("						</div>");
document.writeln("					</a>");
document.writeln("				</div>");
document.writeln("				");
document.writeln("			</div>");